// Code generated by "stringer -type=schedule -output=devmap_string.go"; DO NOT EDIT.

package company

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[none-0]
	_ = x[idea-1]
	_ = x[clarified-2]
	_ = x[interaction-3]
	_ = x[visual-4]
	_ = x[cube-5]
	_ = x[publish-6]
}

const _schedule_name = "noneideaclarifiedinteractionvisualcubepublish"

var _schedule_index = [...]uint8{0, 4, 8, 17, 28, 34, 38, 45}

func (i schedule) String() string {
	if i < 0 || i >= schedule(len(_schedule_index)-1) {
		return "schedule(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _schedule_name[_schedule_index[i]:_schedule_index[i+1]]
}
