// Code generated by "stringer -type=companyname -output=junglemap_string.go"; DO NOT EDIT.

package junglemap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[bear-0]
	_ = x[deer-1]
}

const _companyname_name = "beardeer"

var _companyname_index = [...]uint8{0, 4, 8}

func (i companyname) String() string {
	if i < 0 || i >= companyname(len(_companyname_index)-1) {
		return "companyname(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _companyname_name[_companyname_index[i]:_companyname_index[i+1]]
}
